# Generated by Django 5.2.1 on 2025-05-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('option1', models.CharField(max_length=255, verbose_name='Вариант 1')),
                ('option2', models.CharField(max_length=255, verbose_name='Вариант 2')),
                ('option3', models.CharField(max_length=255, verbose_name='Вариант 3')),
                ('option4', models.CharField(max_length=255, verbose_name='Вариант 4')),
                ('correct_option', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, verbose_name='Правильный вариант')),
            ],
        ),
    ]
